package br.com.itau.bootcamp.event

import com.amazonaws.services.dynamodbv2.datamodeling.*

class KeyEvent {

    @get:DynamoDBHashKey(attributeName = "cpf")
    var cpfOrigem: String? = null

    @get:DynamoDBRangeKey(attributeName = "guid")
    @DynamoDBAutoGeneratedKey
    var guid: String? = null

}